# Generated by Django 5.0.7 on 2024-07-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='celeb',
            new_name='celebrity',
        ),
    ]
