# Generated by Django 5.0.7 on 2024-07-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_rename_celeb_routine_celebrity'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='theme',
        ),
        migrations.AddField(
            model_name='routine',
            name='theme',
            field=models.ManyToManyField(to='search.theme'),
        ),
    ]
