# Generated by Django 5.0.7 on 2024-08-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_alter_routine_category_alter_routine_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='category',
            field=models.ManyToManyField(to='routine.routinecategory'),
        ),
    ]
