# Generated by Django 5.0.7 on 2024-07-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_alter_routine_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='category',
        ),
        migrations.AddField(
            model_name='routine',
            name='category',
            field=models.ManyToManyField(to='routine.routinecategory'),
        ),
    ]
