# Generated by Django 5.0.7 on 2024-07-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_remove_routine_category_routine_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='celebrity',
            new_name='celeb',
        ),
    ]
