# Generated by Django 5.0.7 on 2024-07-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_rename_celebrity_routine_celeb'),
        ('search', '0002_theme_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='theme',
        ),
        migrations.AddField(
            model_name='routine',
            name='theme',
            field=models.ManyToManyField(to='search.theme'),
        ),
    ]
