# Generated by Django 5.0.7 on 2024-07-27 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calen', '0001_initial'),
        ('routine', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='calenderroutine',
            name='calender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calen.calender'),
        ),
        migrations.AddField(
            model_name='calenderroutine',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.routine'),
        ),
    ]
