# Generated by Django 5.0.7 on 2024-07-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calen', '0002_initial'),
        ('routine', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calender',
            new_name='Calendar',
        ),
        migrations.RenameModel(
            old_name='CalenderRoutine',
            new_name='CalendarRoutine',
        ),
        migrations.RenameField(
            model_name='calendarroutine',
            old_name='calender',
            new_name='calendar',
        ),
    ]
