# Generated by Django 5.0.7 on 2024-07-29 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celeb', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('celeb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='celeb.celeb')),
            ],
        ),
    ]
