# Generated by Django 5.0.7 on 2024-07-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('routine', '0003_remove_routine_theme_routine_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_routine_categories',
            field=models.ManyToManyField(blank=True, to='routine.routinecategory'),
        ),
    ]
