# Generated by Django 5.0.7 on 2024-08-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True, default='https://cdn.pixabay.com/photo/2020/08/22/12/36/yoga-5508336_1280.png', null=True)),
            ],
        ),
    ]
