# Generated by Django 5.0.7 on 2024-08-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0001_initial'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='routines',
            field=models.ManyToManyField(blank=True, related_name='celebrities', to='routine.routine'),
        ),
    ]
