# Generated by Django 5.0.7 on 2024-08-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celeb', '0002_alter_celeb_photo'),
        ('celeb', '0002_celeb_routines'),
    ]

    operations = [
    ]
